services:
 mongo-notifications:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_notification_data:/data/db
    
 mysql-user:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_user_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-task:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_task_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 notification-service:
  depends_on:
    - mongo-notifications
  image: mikkyg/notificationservice:1.0
  ports:
    - 8080:8080
  links:
    - mongo-notifications
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-notifications
   
 task-service:
  depends_on:
    - mysql-task
  image: mikkyg/taskservice:1.0
  ports:
    - 8082:8082
  links:
    - mysql-task
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-task
   MYSQL_DB_PORT: 3306

 user-service:
  depends_on:
    - notification-service
    - task-service
  image: mikkyg/userservice:1.0
  ports:
    - 8081:8081
  links:
    - notification-service
    - task-service
  environment:
   PRODUCT_SERVICE_BASEURL: notification-service:8080
   INVENTORY_INFO_SERVICE_BASEURL: task-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-user
   MYSQL_DB_PORT: 3306

 api-gateway:
   depends_on:
     - task-service
   image: mikkyg/ede-api-gateway:latest
   ports:
     - 8083:8083
   links:
     - task-service
   environment:
     TASK_SERVICE_BASEURL: task-service:8082

volumes:
 mongodb_notification_data:
 mysql_task_data:
 mysql_user_data:
