
server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: task-service-get
          uri: http://${TASK_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tasks
            - Method=GET
          filters:
            - SetPath=/tasks
        - id: task-service-post
          uri: http://${TASK_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tasks
            - Method=POST
          filters:
            - SetPath=/tasks
