
server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: task-service-get
          uri: http://${TASK_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tasks
            - Method=GET
          filters:
            - SetPath=/tasks
        - id: task-service-post
          uri: http://${TASK_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tasks
            - Method=POST
          filters:
            - SetPath=/tasks
        - id: task-service-get-by-id
          uri: http://${TASK_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tasks/{id}
            - Method=GET
          filters:
            - SetPath=/tasks/{id}
        - id: task-service-put
          uri: http://${TASK_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tasks/{id}
            - Method=PUT
          filters:
            - SetPath=/tasks/{id}
        - id: task-service-delete
          uri: http://${TASK_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/tasks/{id}
            - Method=DELETE
          filters:
            - SetPath=/tasks/{id}
        - id: user-service-get
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/users
            - Method=GET
          filters:
            - SetPath=/users
        - id: user-service-get-by-id
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/users/{userId}
            - Method=GET
          filters:
            - SetPath=/users/{userId}
        - id: notification-service-get
          uri: http://${NOTIFICATION_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/notifications
            - Method=GET
          filters:
            - SetPath=/notifications
        - id: notification-service-post
          uri: http://${NOTIFICATION_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/notifications
            - Method=POST
          filters:
            - SetPath=/notifications